[package]
name = "sdl2_part1"
version = "0.1.0"
authors = ["bpagis <bru65pag@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.33.0"
# sdl2-sys = "0.33.0"
